### ISSUE TITLE
请把umi升级到2.x

### ISSUE THREAD

**Issue by kztao** [umijs/umi-example-electron#13]
请把umi升级到2.x

**Comment by williamnie** [comment]
可以参照我的例子，让云谦赶紧搞ssr吧😂[https://github.com/williamnie/umi-electron](https://github.com/williamnie/umi-electron)

**Comment by ycjcl868** [comment]
@williamnie  umijs/umi#2543

**Comment by williamnie** [comment]
@ycjcl868 我已经在搞了，上次按照你说的link过去，build以后，还是不行，和我上次报错一样。
我提了issue[umi/issues/2586](https://github.com/umijs/umi/issues/2586)

**Comment by xclw2000** [comment]
什么时候能搞好呀，急着用呀

**Comment by Mi10040** [comment]
什么时候能同步umi 3.0x和TS兼容

**Comment by williamnie** [comment]
> 什么时候能同步umi 3.0x和TS兼容

需要umi3.0的electron ？ 参照这个https://github.com/williamnie/umi3.0-electron
改成ts的就行了

**Comment by Mi10040** [comment]
> > 什么时候能同步umi 3.0x和TS兼容
> 
> 需要umi3.0的electron ？ 参照这个https://github.com/williamnie/umi3.0-electron
> 改成ts的就行了

这样集成进electron中对主线程的node兼容TS处理有些差劲特别是在umi使用ES规范而主线程依然是CommonJS规范，这也就是为什么希望umi官方可以把electron完全可以嵌入进去统一编码的原因

**Comment by williamnie** [comment]
> > > 什么时候能同步umi 3.0x和TS兼容
> > 
> > 
> > 需要umi3.0的electron ？ 参照这个https://github.com/williamnie/umi3.0-electron
> > 改成ts的就行了
> 
> 这样集成进electron中对主线程的node兼容TS处理有些差劲特别是在umi使用ES规范而主线程依然是CommonJS规范，这也就是为什么希望umi官方可以把electron完全可以嵌入进去统一编码的原因

node现在都还没有完全支持es规范，而且umi怎么把electron完全嵌入进去？可以自己配webpack吧

**Comment by yunsii** [comment]
今天折腾一天，搞定了 umi@3.x  + typescript@4.x + electron@11.x，参考 https://github.com/kit48/electron-pro \_(:3J∠)\_
